config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :birds, only: [:index, :new, :create, :show, :edit, :update]
  resources :locations, only: :index
end

app/models/bird.rb
class Bird < ActiveRecord::Base
  # Paperclip:
  has_attached_file :photo, styles: { medium: "300x300>", thumbnail: "100x100>"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  #validates presence of :attribution if photo

  has_many :bird_locations
  has_many :locations, through: :bird_locations

  attr_reader :photo_remote_url

  def photo_remote_url=(remote_url)
    if remote_url
      self.photo = URI.parse(remote_url)
      self.url = remote_url #save the original url for later, too
    end
      @photo_remote_url = remote_url
  end
end

app/models/bird_location.rb
class BirdLocation < ActiveRecord::Base
  belongs_to :bird
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, presence: true

  has_many :bird_locations
  has_many :birds, through: :bird_locations


  def ebird_link
    "http://ebird.org/ebird/hotspot/" + ebird_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
 helper_method :sort_column, :sort_direction

  def index
    sort = sort_column + ' ' + sort_direction
    @birds = Bird.order(sort )
  end

  def new
    @bird = Bird.new
  end

  def create
    bird = Bird.new(bird_params)
    if bird.save
      redirect_to bird_path(bird)
    else
      render :new
    end
  end

  def show
    @bird = Bird.find(params[:id])
  end

  def edit
    @bird = Bird.find_by_id(params[:id])
  end

  def update
    bird = Bird.find_by_id(params[:id])

    if bird.update_attributes(bird_params)
      redirect_to bird_path(bird)
    else
      render edit_bird_path(bird)
    end
  end

  private
  def bird_params
    params.require(:bird).permit(:photo_remote_url, :attribution, :name, :description, :priority, :number_of_locations)
  end

  def sort_column
   %w(name number_of_locations priority).include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
     %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def t_f?(val)
    val ? "Yes" : "No"
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, sort: column, direction: direction
  end
end

app/views/birds/_form.html.erb
<%= form_for bird, url: {action: action} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_remote_url %>

  <%= f.label :photo_credit %>
  <%= f.text_field :attribution %>

  <%= f.label :number_of_locations %>
  <%= f.number_field :number_of_locations, in: 1..20, step: 1 %>

  <%= f.label :priority %>
  <%= f.label "Yes" %>
  <%= f.radio_button :priority, true %>
  <%= f.label "No" %>
  <%= f.radio_button :priority, false, {checked: true} %>

  <br>

  <%= f.submit %>
<% end %>

app/views/birds/edit.html.erb
<%= form_for @bird, url: bird_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_remote_url %>

  <%= f.label :photo_credit %>
  <%= f.text_field :attribution %>

  <%= f.label :number_of_locations %>
  <%= f.number_field :number_of_locations, in: 1..20, step: 1 %>

  <%= f.label :priority %>

  <%= f.label :priority_yes, "Yes" %>
  <%= f.radio_button :priority, true %>
  <%= f.label :priority_no, "No" %>
  <%= f.radio_button :priority, false, {checked: true} %>

  <br>
  <%= f.submit %>
<% end %>

app/views/birds/index.html.erb
<div id='bird-index'>
  <h1>Click the Name of a bird to see a larger picture.</h1>

  <table>
    <thead>
      <th></th>
      <th><%= sortable 'name' %></th>
      <th>Photo</th>
      <th><%= sortable 'number_of_locations' %></th>
      <th><%= sortable 'priority' %></th>
    </thead>
    <tbody>
      <% count = 1 %>
      <% @birds.each do |bird| %>
      <tr>
        <td><%= count %></td>
        <td><%= link_to bird.name, bird_path(bird) %></td>
        <td>
          <% if bird.photo_file_name %>
            <%= image_tag(bird.photo.url(:thumbnail)) %>
            <p class="photo-credit"><span>Photo Credit: </span><%= bird.attribution %></p>
          <% end %>
        </td>
        <td><%= bird.number_of_locations %></td>
        <td><%= t_f?(bird.priority) %></td>
      </tr>
      <% count += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/birds/new.html.erb
<%= render partial: "form", locals: {bird: @bird, action: "create"} %>

app/views/birds/show.html.erb
<div id='bird-show'>

  <%= link_to 'Back to All Birds', birds_path, class: 'go-back' %>

  <h1><%= @bird.name %></h1>

  <% if @bird.priority %>
  <h4>Priority Bird</h4>
  <% end %>

  <p>Seen at <span class='count'><%= @bird.number_of_locations %></span> locations in April-June </p>

  <% if @bird.flickr_url %>
  <%= link_to 'View the photo on Flickr', @bird.flickr_url %>
  <% end %>

  <% if @bird.photo_file_name %>
    <div class='photo-floating'>
      <%= image_tag @bird.photo.url(:medium) %>
      <p class="photo-credit"><span>Photo Credit: </span><%= @bird.attribution %></p>
    </div>
  <% end %>

  <% if @bird.description %>
    <p><%= @bird.description %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CostaRicaBirds</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='title-bar' class='container'>
    <h1 id='title'><%= link_to "Birds of Costa Rica", root_path %></h1>
    <h2 id='subtitle'>Explore the birds we might see while on our Reefs To Rockies Birding Trip!</h2>
    <hr>
  </div>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/locations/index.html.erb
<% @locations.each do |loc| %>
<h4><%= loc.name %></h4>

<% if loc.website %>
  <%= link_to "location website", "http://#{loc.website}" %>
<% end %>

<br>
<br>
<a href=<%= loc.ebird_link %> >Check it out on eBird!</a>
<hr>
<% end %>

app/views/pages/home.html.erb
<p>
  Birds were chosen and organized by the number of locations they were observed at in April-June, based on eBird reports. 7 sites that we'll be visiting were used.

  To see a list of those locations, please visit the <%= link_to 'Locations Page', locations_path %>.
</p>

<p>
  <span class='note'>What is a Priority Species?</span> These are species that were seen at most of the sites we'll be visiting, or are unique (or just plain cool!) birds.
</p>

<br><br>

<h2>
  <%= link_to 'Check out the Birds!', birds_path %>
</h2>

<br><br>

<p class='note'>Note: This app is meant for personal study only. Not intended for commerical use.</p>